inventory_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('', views.home, name='home')
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('products/', include('productapp.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='productapp:product_list'), name='logout'),
]

productapp/urls.py
from django.urls import path, re_path

from productapp import views

app_name = 'productapp'

urlpatterns=[
    path('', views.product_list, name='product_list'), # localhost/product/
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'), # localhost/product/1
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'), # localhost/product/1/1
    re_path(r'^new/$', views.ProductCreate.as_view(), name='product_new'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/delete/$', views.ProductDelete.as_view(), name='confirm_delete'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/update/$', views.ProductUpdate.as_view(), name='product_update'),

]

productapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse_lazy, reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str(self):
        return self.name

    def get_absolute_url(self):
        return reverse('productapp:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='media', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('productapp:product_detail', args=[self.id, self.slug])

productapp/views.py
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from productapp.models import Product, Category
from django.urls import reverse_lazy


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'productapp/product_list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    return render(request,
                  'productapp/product_detail.html', {'product': product})


class ProductCreate(CreateView):
    model = Product
    # form_class = BlogForm
    fields = ['name', 'category', 'description', 'price'] #form
    template_name = 'productapp/product_new.html'
    success_url = reverse_lazy('productapp:product_list') # reverse map a url -

class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('productapp:product_list')

class ProductUpdate(UpdateView):
    model = Product
    fields = ['name', 'category', 'description', 'price']
    template_name = 'productapp/product_new.html'
    success_url = reverse_lazy('productapp:product_list')

productapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}HOME{% endblock title %}</title>
</head>
<body>
        <div id="header">
    </div>
    <div>
        <table width="100%">
            <tr>
                <td colspan="75%"><a href="{% url 'productapp:product_list' %}"> HOME </a></td>
                <td colspan="25%">
                    {% if user.is_authenticated %}
                        <p><a href="{% url 'logout' %}">Log Out</a></p>
                    {% else %}
                        <p><a href="{% url 'login' %}">Log In</a></p>
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
    <div>
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

productapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block content %}
    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
    {% if redirect_field_name %}
          <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_name }}">
    {% else %}
          <input type="hidden" name="next" value="{{ next }}">
    {% endif %}
</form>

{% endblock %}
</body>
</html>

productapp/templates/productapp/product_confirm_delete.html
<form method="post">{% csrf_token %}

<p>Are you sure you want to delete "{{ object }}"?</p>

    <input type="submit" value="Confirm">
</form>

productapp/templates/productapp/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

productapp/templates/productapp/product_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "productapp:product_list" %}">All</a>
            </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        <table>
        {% for product in products %}
            <tr>
                <div class="item">

                    <th><a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a></th>

                    <th><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></th>
                    <th>${{ product.price }}<th/>
                    <th><a href="{% url 'productapp:product_update' product.id product.slug%}">Update</a></th>
                    <th><a href="{% url 'productapp:confirm_delete' product.id product.slug%}">Delete</a></th>
                </div>
            </tr>
        {% endfor %}
            <tr><a href="new/">Create New Product</a></tr>
        </table>
    </div>
{% endblock %}

productapp/templates/productapp/product_new.html
{% extends '../base.html' %}

{% block title %}Create New Product{% endblock title %}

{% block content %}
    <form method="post" action="{% url 'productapp:product_new' %}">{% csrf_token %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'productapp:product_list' %}" > Cancel </a>
    </form>
{% endblock content %}

productapp/templates/productapp/product_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update"><form method="post" action="{% url 'productapp:product_update' %}">{% csrf_token %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Update">Update</button>
        <a href="{% url 'productapp:product_list' %}" > Cancel </a>
</form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django{% endblock title %}</title>
</head>
<body>
    <div>
        <table width="100%">
            <tr>
                <td colspan="75%"><a href="{% url 'productapp:product_list' %}"> HOME </a></td>
                <td colspan="25%">
                    {% if user.is_authenticated %}
                        <p><a href="{% url 'logout' %}">Log Out</a></p>
                    {% else %}
                        <p><a href="{% url 'login' %}">Log In</a></p>
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
    <div>
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

templates/productapp/category_list.html
{% extends '../base.html' %}

{% block title %}Product List{% endblock title %}

{% block content %}
{{ products }}
    {% if products %}
        <table>
        {% for product in products %}
            <tr><td>&nbsp;&nbsp;&nbsp;</td><td><a href="{% url 'productapp:product_detail' product.id.id %}">{{ product.product_name }}</a></td>

                <td><a href="{% url 'productapp:product_update' product.id %}" > Edit </a></td></tr>
            {% empty %}
        {% endfor %}
        </table>
    {% else %}
        <p>No products are available.</p>
    {% endif %}
{% endblock content %}